### PR TITLE
SMD Version with upgraded mega644

### PR DESCRIPTION
**Pull request by buserror**
This is a straight derivative version with most small parts converted to
    SMT. Also all using footprints and references from JLPCB, so as of
    today, you can order a fully built card; it'll just be missing the
    Atmega, which is not in stock, but is easy to add...
    
    I still used the 'hand soldering' footprints from Kicad so it should be
    easy to modify and rework.
    
    Oh also, I simplified some things, re-layout the schemastic on an A3
    sheet, and replaced diodes with a LDO with good filtering, that should
    improve SD card compatibility.
    
    I removed some test headers, re-layouted all the connectors at the top,
    and moved the LEDs at the front.
    
    To amuse myself I tried to layout the board in a 'classic'
    vertical/horizontal pattern of traces, so it's not 'cheap' on VIAs, but
    it looks cool! :-)

### CODE REVIEW

**Comment by ThorstenBr** [comment]
I'm going to have a look at this. Did you adapt something in the MiniCore/bootloader project in order to build the bootloader for the mega644? Could you also provide the changes you needed to do there for the 644 - in case the bootloaders ever need to be rebuilt?

**Comment by buserror** [comment]
> I'm going to have a look at this. Did you adapt something in the MiniCore/bootloader project in order to build the bootloader for the mega644? Could you also provide the changes you needed to do there for the 644 - in case the bootloaders ever need to be rebuilt?

Well I followed your instructions, the command I used is in the Makefile on this PR, along with the name of the bootloader. I checked the source, the pin 'mapping' is exactly the same so I assume it will just work!

**Comment by buserror** [comment]
I've just noticed you pushed some changes, I haven't rebased on this and github sees a conflict -- do you want me to rebase, resolve the problem and re-submit or are you OK doing it?

EDIT: I used the github interface to resolve the conflict, it was minor

**Comment by ThorstenBr** [comment]
Ok, I have merged this - thanks! :)

Some comments/suggestions:
- I couldn't open the kicad project (I need to update my KiCad again), but I would suggest to change the pull-down resistors which are connected to the 8255 (R2/R3/R18/7/21/22/R23) to 4k7 instead of 10k. We recently discussed this in the Fritter forum (including Daniel). The 10k are actually out of spec (not matching the 8255 datasheet, which specifies a minimum required current to overcome the "bus hold" logic of the 8255 port pins). And while most 8255s still work with the 10k pull-downs, some are known not to work (especially none of the 82C55s made by Harris will work). But it's not the chip's fault, but the PCB's (resistors too weak). I have an updated version of the atmega328 PCB+schematics (which I will push soon), where I also changed these resistors to 4k7.

- With the next PCB update I will remove all the individual Gerber files (.gbr) from the project. I think the ZIP file is enough, since no one really wants to look at the diff of the individual files. What everyone just wants is the ZIP file, so it can be quickly downloaded - and uploaded to JLCPCB etc. With the next update maybe add the "644" and a version suffix to the Gerber ZIP file (e.g. "Apple2Card_644_v1.1.1.zip" etc). Just use the version which is also visible on the PCB. Since this is being directly downloaded, it's helpful if one can immediately see the variant and version contained in the (downloaded) ZIP file.

- Your ".bash_history" files were accidentally added. :) That's actually a "classic issue" - which has sometimes caused leaks of private information (passwords etc). There was nothing sensitive in your history though - so I just deleted them again (without rewriting the commits).

**Comment by buserror** [comment]
Thanks! 
* Yes I used Kicad 7.0.6, which comes with Debian sid -- I hadn't used it for a while, I hadn't realised it was 'bleeding edge' (that surprises me from Debian!) -- However I was well impressed ny it TBH, the schematic editor in particular was a pleasant upgrade, very easy to rework stuff.
* Good plan (remove the gerbber) -- and yes I kept the 'jlpcb' directory as it's nice and clean, and has the jlpcb plugin output (including part mapping and rotation). There's plenty of files in that project dir that I have no idea if they ought to be kept, or if they are intermediate files! Kicad is a bit 'noisy' like that.
* Ahah yeah .bash_history -- I had found on in the source code dir too, missed the other one. I recently changed to 'local history' as I have so many projects, it makes sense but I'm not liking the turd files either. Might changed the system to use a central place (and a hash) to keep the files around!

Thanks for the merge, I'm keeping this fork around and continue to push and do PRs if you don't mind

**Pull request closed without merging**
